export const users = [
    {
        id:1,
        login:'John Doe',
        email:'JohnDoe@gmail.com',
        password:'1234',
        profilpic_path:'/public/images/1662650_1.jpg'
    },
    {
        id:2,
        login:'Anya',
        email:'Anya@gmail.com',
        password:'3452',
        profilpic_path:'/public/images/anya.png'
    },
    {
        id:3,
        login:'Mob',
        email:'Mob@gmail.com',
        password:'0502',
        profilpic_path:'/public/images/mob.png'
    },
    {
        id:4,
        login:'Mercredi',
        email:'Mercrediadams@gmail.com',
        password:'0502',
        profilpic_path:'/public/images/mercredi.png'
    },
    {
        id:5,
        login:'Imarioa',
        email:'imarioa@gmail.com',
        password:'0502',
        profilpic_path:'/public/images/imarioa.jpg'
    },
    {
        id:6,
        login:'Bakugo',
        email:'young_bakugo@gmail.com',
        password:'0502',
        profilpic_path:'/public/images/bakugo.jpg'
    },
    {
        id:7,
        login:'Yuta',
        email:'Yuta@gmail.com',
        password:'0502',
        profilpic_path:'/public/images/yuta.jpg'
    },
    {
        id:8,
        login:'Miles',
        email:'Miles_Morales@gmail.com',
        password:'0502',
        profilpic_path:'/public/images/images.jpg'
    },
]